# Generated by Django 3.0.6 on 2020-06-29 08:15

import datetime

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='EmployeeTasks',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Task Name')),
                ('description', models.CharField(blank=True, max_length=200, null=True, verbose_name='Description')),
                ('status',
                 models.CharField(choices=[('0', 'New'), ('1', 'In Progress'), ('2', 'Completed')], default='0',
                                  max_length=1, verbose_name='Task Status')),
                ('created_at', models.DateTimeField(default=datetime.datetime(2020, 6, 29, 8, 15, 34, 42800))),
                ('modified_at', models.DateTimeField(default=datetime.datetime(2020, 6, 29, 8, 15, 34, 42881))),
                ('employee',
                 models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
