# Generated by Django 3.0.6 on 2020-06-29 08:16

import datetime

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('employee_management_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employeetasks',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2020, 6, 29, 8, 16, 2, 908929)),
        ),
        migrations.AlterField(
            model_name='employeetasks',
            name='modified_at',
            field=models.DateTimeField(default=datetime.datetime(2020, 6, 29, 8, 16, 2, 908955)),
        ),
    ]
